# Airbnb London Data Exploration

This notebook loads the London Airbnb raw data and inspects the main tables used in the analysis.

In [1]:
import pandas as pd

listings = pd.read_csv("../data/raw/listings.csv")
calendar = pd.read_csv("../data/raw/calendar.csv")
reviews = pd.read_csv("../data/raw/reviews.csv")
neighbourhoods = pd.read_csv("../data/raw/neighbourhoods.csv")

In [20]:
listings.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20260614073253,2026-06-15,city scrape,11 Min to Manhattan • Prospect Park • Fast WiFi,"Bright, serene room in a renovated apartment h...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,2787,...,5.00,4.78,4.78,NaN,NaN,5,0,5,0,0.08
1,6848,https://www.airbnb.com/rooms/6848,20260614073253,2026-06-14,city scrape,Only 2 stops to Manhattan studio,Comfortable studio apartment with super comfor...,NaN,https://a0.muscache.com/pictures/e4f031a7-f146...,15991,...,4.80,4.69,4.59,NaN,NaN,1,1,0,0,0.95
2,6872,https://www.airbnb.com/rooms/6872,20260614073253,2026-06-14,city scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,16104,...,5.00,5.00,5.00,NaN,NaN,2,0,2,0,0.04
3,6990,https://www.airbnb.com/rooms/6990,20260614073253,2026-06-14,city scrape,UES Beautiful Blue Room,Beautiful peaceful healthy home,NaN,https://a0.muscache.com/pictures/45fb4ec7-6856...,16800,...,4.94,4.85,4.84,NaN,NaN,1,0,1,0,1.24
4,7097,https://www.airbnb.com/rooms/7097,20260614073253,2026-06-14,city scrape,"Perfect for Your Parents, With Garden & Patio",Parents/grandparents coming to town or are you...,NaN,https://a0.muscache.com/pictures/aaac19fc-4b4d...,17571,...,4.93,4.95,4.82,NaN,NaN,2,0,2,0,2.12

In [7]:
calendar.head()

   listing_id        date available  minimum_nights  maximum_nights
0      115535  2026-06-14         f              30             365
1      115535  2026-06-15         t              30             365
2      115535  2026-06-16         f              30             365
3      115535  2026-06-17         f              30             365
4      115535  2026-06-18         f              30             365

In [8]:
reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,2539,55688172,2015-12-04,25160947,Peter,Great host
1,2539,97474898,2016-08-27,91513326,Liz,Nice room for the price. Great neighborhood. J...
2,2539,105340344,2016-10-01,90022459,Евгений,Very nice apt. New remodeled.
3,2539,133131670,2017-02-20,116165195,George,Great place to stay for a while. John is a gre...
4,2539,138349776,2017-03-19,118432644,Carlos,.

In [9]:
neighbourhoods.head()

  neighbourhood_group neighbourhood
0               Bronx      Allerton
1               Bronx    Baychester
2               Bronx       Belmont
3               Bronx     Bronxdale
4               Bronx   Castle Hill

In [10]:
print(listings.shape)

(30259, 90)

In [11]:
print(calendar.shape)

(11152576, 5)

In [12]:
print(reviews.shape)

(990170, 6)

In [13]:
print(neighbourhoods.shape)

(230, 2)

In [14]:
listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 30259 entries, 0 to 30258
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            30259 non-null  int64
 1   listing_url                                   30259 non-null  str
 2   scrape_id                                     30259 non-null  int64
 3   last_scraped                                  30259 non-null  str
 4   source                                        30259 non-null  str
 5   name                                          30258 non-null  str
 6   description                                   29357 non-null  str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   30259 non-null  str
 9   host_id                                       30259 non-null  int64
 10  host_url                                      30259 non-null  str
 11  host_profile_id                               29910 non-null  float64
 12  host_profile_url                              29910 non-null  str
 13  host_name                                     29910 non-null  str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      29910 non-null  float64
 16  hosts_time_as_user_months                     29910 non-null  float64
 17  hosts_time_as_host_years                      29910 non-null  float64
 18  hosts_time_as_host_months                     29910 non-null  float64
 19  host_location                                 23097 non-null  str
 20  host_about                                    17849 non-null  str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             29910 non-null  str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              29910 non-null  str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           29910 non-null  float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          29910 non-null  str
 32  host_identity_verified                        29910 non-null  str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        30259 non-null  str
 35  neighbourhood_group_cleansed                  30259 non-null  str
 36  latitude                                      30259 non-null  float64
 37  longitude                                     30259 non-null  float64
 38  property_type                                 30259 non-null  str
 39  room_type                                     30259 non-null  str
 40  accommodates                                  30259 non-null  int64
 41  bathrooms                                     20147 non-null  float64
 42  bathrooms_text                                30100 non-null  str
 43  bedrooms                                      19286 non-null  float64
 44  beds                                          20839 non-null  float64
 45  amenities                                     30259 non-null  str
 46  price                                         21515 non-null  str
 47  price_quote_checkin_date                      22678 non-null  str
 48  price_quote_checkout_date                     22678 non-null  str
 49  price_quote_total_price                       21514 non-null  float64
 50  price_quote_price_per_night                   21514 non-null  float64
 51  price_quote_raw                               22678 non-null  str
 52  minimum_nights                                30257 non-null  float64
 53  maximum_nights                                30257 non-null  float64
 54  minimum_minimum_nights                        30257 non-null  float64
 55  maximum_minimum_nights                        30257 non-null  float64
 56  minimum_maximum_nights                        30257 non-null  float64
 57  maximum_maximum_nights                        30257 non-null  float64
 58  minimum_nights_avg_ntm                        30259 non-null  float64
 59  maximum_nights_avg_ntm                        30259 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              29912 non-null  str
 62  availability_30                               30259 non-null  int64
 63  availability_60                               30259 non-null  int64
 64  availability_90                               30259 non-null  int64
 65  availability_365                              30259 non-null  int64
 66  calendar_last_scraped                         30259 non-null  str
 67  number_of_reviews                             30259 non-null  int64
 68  number_of_reviews_ltm                         30259 non-null  int64
 69  number_of_reviews_l30d                        30259 non-null  int64
 70  availability_eoy                              30259 non-null  int64
 71  number_of_reviews_ly                          30259 non-null  int64
 72  estimated_occupancy_l365d                     30259 non-null  int64
 73  estimated_revenue_l365d                       21515 non-null  float64
 74  first_review                                  21700 non-null  str
 75  last_review                                   21700 non-null  str
 76  review_scores_rating                          21700 non-null  float64
 77  review_scores_accuracy                        21694 non-null  float64
 78  review_scores_cleanliness                     21700 non-null  float64
 79  review_scores_checkin                         21692 non-null  float64
 80  review_scores_communication                   21697 non-null  float64
 81  review_scores_location                        21691 non-null  float64
 82  review_scores_value                           21691 non-null  float64
 83  license                                       5286 non-null   str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                30259 non-null  int64
 86  calculated_host_listings_count_entire_homes   30259 non-null  int64
 87  calculated_host_listings_count_private_rooms  30259 non-null  int64
 88  calculated_host_listings_count_shared_rooms   30259 non-null  int64
 89  reviews_per_month                             21700 non-null  float64
dtypes: float64(42), int64(18), str(30)
memory usage: 82.7 MB

In [15]:
listings.describe()

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,3.025900e+04,3.025900e+04,0.0,3.025900e+04,2.991000e+04,0.0,29910.000000,29910.000000,29910.000000,29910.000000,...,21692.000000,21697.000000,21691.000000,21691.000000,0.0,30259.000000,30259.000000,30259.000000,30259.000000,21700.000000
mean,6.172513e+17,2.026061e+13,NaN,2.672815e+15,1.469574e+18,NaN,8.284754,5.653928,6.684286,5.631829,...,4.838066,4.821284,4.743640,4.633094,NaN,55.887141,45.630721,9.146601,0.095905,0.846505
std,6.155147e+17,0.000000e+00,NaN,6.705743e+16,2.417060e+16,NaN,3.934796,3.482520,3.889389,3.356700,...,0.373301,0.418090,0.388374,0.496439,NaN,174.246090,172.331916,36.412035,1.125182,1.847935
min,2.539000e+03,2.026061e+13,NaN,1.678000e+03,1.462506e+18,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,3.038760e+07,2.026061e+13,NaN,2.069159e+07,1.462882e+18,NaN,5.000000,3.000000,3.000000,3.000000,...,4.827500,4.820000,4.660000,4.530000,NaN,1.000000,0.000000,0.000000,0.000000,0.090000
50%,6.608782e+17,2.026061e+13,NaN,1.074344e+08,1.465524e+18,NaN,9.000000,6.000000,7.000000,5.000000,...,4.950000,4.960000,4.850000,4.760000,NaN,2.000000,1.000000,0.000000,0.000000,0.270000
75%,1.160901e+18,2.026061e+13,NaN,3.948700e+08,1.469572e+18,NaN,11.000000,9.000000,10.000000,8.000000,...,5.000000,5.000000,5.000000,4.920000,NaN,12.000000,3.000000,2.000000,0.000000,0.962500
max,1.707075e+18,2.026061e+13,NaN,1.704453e+18,1.706707e+18,NaN,17.000000,11.000000,15.000000,11.000000,...,5.000000,5.000000,5.000000,5.000000,NaN,955.000000,955.000000,231.000000,22.000000,115.630000

In [16]:
listings.isnull().sum().sort_values(ascending=False)

neighborhood_overview                           30259
host_since                                      30259
host_response_time                              30259
host_thumbnail_url                              30259
host_acceptance_rate                            30259
                                                ...
availability_30                                     0
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
Length: 90, dtype: int64

In [17]:
listings.duplicated().sum()

np.int64(0)

In [18]:
calendar.duplicated().sum()

np.int64(0)

In [19]:
reviews.duplicated().sum()

np.int64(0)